# theme = "modster"
theme = "modster-bright"

[editor.cursor-shape]
insert = "bar"
select = "underline"
normal = "bar"

[editor.soft-wrap]
enable = true

[editor]
# auto-completion = false
# idle-timeout = 1200
bufferline = "always"
color-modes = true
cursorcolumn = true
cursorline = true
gutters = ["diagnostics", "line-numbers", "spacer"]
preview-completion-insert = false
rulers = [100]
scroll-lines = 1
scrolloff = 4

[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "register"]
center = ["file-name", "diagnostics"]
right = [
  "selections",
  "file-encoding",
  "position",
  "total-line-numbers",
  "position-percentage",
]

[editor.lsp]
# prevent auto popup documentation while typing when =false
# auto-signature-help = false
display-inlay-hints = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
# tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎"

[editor.file-picker]
max-depth = 3

[keys.normal]
"C-/" = "toggle_comments" # [1]
# "C-r" = "rotate_view"
"A-P" = ["command_palette"]
"tab" = ["insert_mode"]
"backspace" = ["delete_char_backward", "insert_mode"]
"esc" = ["collapse_selection", "keep_primary_selection"]
"p" = ["paste_before", "collapse_selection", "keep_primary_selection"]
"P" = [
  ":clipboard-paste-before",
  "collapse_selection",
  "keep_primary_selection",
]
"del" = ["delete_char_forward", "insert_mode"]
"A-c" = "no_op"
"A-space" = "code_action"

[keys.select]
# j = { k = "normal_mode" }
J = { K = "normal_mode" }
"A-ret" = "normal_mode"

[keys.select.j]
k = "normal_mode"
[keys.insert.j]
k = "normal_mode"

[keys.insert]
# j = { k = "normal_mode" }
J = { K = "normal_mode" }

"C-/" = "toggle_comments" # [1]
"C-c" = "toggle_comments"

"A-ret" = "normal_mode"
"A-h" = ["move_char_left"]
"A-j" = ["move_line_down"]
"A-k" = ["move_line_up"]
"A-l" = ["move_char_right"]
"A-space" = ["completion"]

[keys.insert."A-g"]
l = ["goto_line_end"]
h = ["goto_line_start"]
p = ["paste_before"]
u = ["normal_mode", "undo"]
U = ["normal_mode", "redo"]

# Prompt for custom menu
[keys.normal.g]
"]" = ["goto_next_buffer"]
"[" = ["goto_previous_buffer"]

# [1] requires enhanced keyboard protocol
# https://github.com/helix-editor/helix/wiki/Terminal-Support#enhanced-keyboard-protocol
# https://wezfurlong.org/wezterm/config/key-encoding.html#kitty-keyboard-protocol
