[language-server.pylsp]
# pycodestyle = { ignore = ["W292", "W293", "E501", "E128"] }

[[language]]
name = "python"
formatter = { command = "black", args = ["--preview", "--quiet", "-"] }
# formatter = { command = "black", args = ["-"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true
