
"attribute" = "bogster-orange"
"namespace" = { fg = "bogster-red" }

"keyword" = { fg = "bogster-yellow" }
"keyword.directive" = { fg = "bogster-lyellow", modifiers = ["italic"] }
"keyword.control" = { fg = "bogster-lyellow" }

"punctuation" = { fg = "bogster-fg1" }
"punctuation.delimiter" = { fg = "bogster-fg1", modifiers = ["bold"] }
"punctuation.special" = { fg = "bogster-yellow", modifiers = ["bold"] }
"operator" = { fg = "bogster-fg1", modifiers = ["bold"] }

# e.g. see highlighting for match texted in file-picker
"special" = "#88C0D0"
"tag" = { fg = "bogster-fg0" }


"variable.other.member" = "#88C0D0"
"variable" = "bogster-fg0"
"variable.parameter" = { fg = "bogster-fg0", modifiers = ["italic"] }
"type" = "bogster-lred"
"type.builtin" = { fg = "bogster-red" }
"constructor" = "bogster-lred"
"function" = { fg = "#82A6CF" }
"function.macro" = { fg = "bogster-orange", modifiers = ["bold"] }
# "function.builtin" = { fg = "bogster-lblue", modifiers = ["bold"] }
"function.builtin" = { fg = "#82A6CF", modifiers = ["bold"] }

"comment" = { fg = "bogster-base5", modifiers = ["italic"] }
"variable.builtin" = "bogster-fg0"
"constant" = "bogster-teal"
"constant.builtin" = "bogster-teal"
"string" = { fg = "#7FB685" }
"constant.numeric" = { fg = "#B48EAD", modifiers = ["bold"] }
"constant.character.escape" = { fg = "bogster-teal" }

"label" = "bogster-blue"

"module" = "bogster-red"

"markup.heading" = "bogster-lyellow"
"markup.list" = "bogster-red"
"markup.bold" = { fg = "bogster-yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "bogster-purp", modifiers = ["italic"] }
"markup.link.url" = { fg = "bogster-yellow", modifiers = ["underlined"] }
"markup.link.text" = "bogster-red"
"markup.quote" = "bogster-teal"
"markup.raw" = "bogster-lgreen"


"diff.plus" = "bogster-teal"
"diff.delta" = "bogster-orange"
"diff.minus" = "bogster-lred"

"ui.background" = { bg = "modster-base0" }
"ui.linenr" = { fg = "#6B717E" }
"ui.linenr.selected" = { fg = "bogster-yellow" }

# Documentation popups (e.g Space + k)
"ui.popup" = { bg = "modster-base3" }
# Border lines separating splits
"ui.window" = { bg = "modster-base1" }
# Description box for commands
"ui.help" = { bg = "modster-base1", fg = "bogster-fg1" }

# see ':' menu
"ui.menu" = { fg = "bogster-fg1", bg = "modster-base3" }
"ui.menu.selected" = { bg = "modster-base1", fg = "bogster-yellow", modifiers = [
  "italic",
] }

"ui.cursorline" = { bg = "modster-base3" }
"ui.cursorline.primary" = { bg = "modster-base1" }
# primary, secondary selectors don't seem to work?
# "ui.cursorcolumn.primary" = { bg = "#11123D" }
"ui.cursorcolumn.secondary" = {}

"ui.statusline" = { fg = "bogster-fg1", bg = "modster-base1" }
"ui.statusline.inactive" = { fg = "#A6A09A", bg = "#0E1933" }


"ui.statusline.normal" = { fg = "bogster-base1", bg = "#838EAF", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { fg = "bogster-base1", bg = "#0FFF95", modifiers = [
  "bold",
] }
"ui.statusline.select" = { fg = "bogster-fg1", bg = "bogster-red", modifiers = [
  "bold",
] }

"ui.text" = { fg = "bogster-fg1" }
# e.g. focused item in places such as file picker
"ui.text.focus" = { fg = "bogster-yellow", modifiers = ["bold"] }
"ui.virtual.whitespace" = "bogster-base5"
"ui.virtual.ruler" = { bg = "bogster-base0" }

# see: <Space> mode prompt and '[' & ']' prompt
# "ui.text.info" = { bg = "#662277", fg = "#0000ff" }

# Prompt for multiple key options
# "ui.popup.info" = { bg = "modster-base1", fg = "#aa0000" }

# For selections in the editing area
"ui.selection" = { bg = "selection-bg" }

"ui.cursor.match" = { fg = "bogster-base3", bg = "bogster-orange" }
"ui.cursor" = { fg = "bogster-base5", modifiers = ["reversed"] }


# "warning" = "bogster-orange"
"warning" = "#F0955C"
"error" = "bogster-lred"
"info" = "bogster-teal"
"hint" = "bogster-blue"

# make diagnostic underlined, to distinguish with selection text.
"diagnostic.warning".underline = { color = "#F0955C", style = "curl" }
"diagnostic.error".underline = { color = "bogster-red", style = "curl" }
"diagnostic.info".underline = { color = "bogster-teal", style = "curl" }
"diagnostic.hint".underline = { color = "bogster-blue", style = "curl" }


[palette]
bogster-yellow = "#dcb659"
bogster-lyellow = "#F2D488"
bogster-lblue = "#59dcd8"
bogster-teal = "#59dcb7"
bogster-blue = "#36b2d4"
bogster-orange = "#dc7759"
bogster-red = "#dc597f"
bogster-lgreen = "#7FB685"
bogster-lred = "#FE6D73"
bogster-purp = "#b759dc"

bogster-base0 = "#13181e"
bogster-base1 = "#161c23"
bogster-base2 = "#232d38"
bogster-base3 = "#313f4e"
bogster-base4 = "#415367"
bogster-base5 = "#abb2bf"

bogster-fg0 = "#c6b8ad"
bogster-fg1 = "#D8DEE9"

modster-base0 = "#0c1426"
modster-base1 = "#132145"
modster-base2 = "#253B7A"
modster-base3 = "#1D3354"

selection-bg = "#564787"
