# modster-light; my light theme
"attribute" = "#0D6B70"
"keyword" = { fg = "#5863F8" }
"keyword.directive" = "#393D3F"
"keyword.control" = { fg = "#2D6A75" }
# The type of something, class, function, var, let, etc.
"keyword.storage.type" = { fg = "#8A3258" }

"punctuation" = { fg = "#000000" }
"punctuation.delimiter" = { fg = "#000000" }
"punctuation.special" = { fg = "#000000" }
"operator" = { fg = "#393D3F", modifiers = ["dim"] }
"special" = "#D90368"

"variable" = "#1A3A3A"
"variable.builtin" = { fg = "#1A3A3A", modifiers = ["italic"] }
"variable.parameter" = { modifiers = ["italic"] }
# Fields of composite data types (e.g. structs, unions)
"variable.other.member" = { fg = "#8A3258" }

"type" = "#1A3A3A"
"type.enum" = "#0D6B70"


"function" = { fg = "#275DAD" }
"function.builtin" = { modifiers = ["italic"] }
"function.method" = { fg = "#275DAD" }
"function.macro" = { fg = "#D90368" }
"comment" = { fg = "#7D8F7A", modifiers = ["italic"] }
"constant" = "#8A3258"

"string" = "#32936F"
"constant.character.escape" = { fg = "#ff0000", modifiers = ["bold"] }
"string.special" = "#ff0000"
"label" = "#ff0000"
"module" = "bogster-red"

"markup.heading" = "#020887"
"markup.list" = "bogster-red"
"markup.bold" = { fg = "#1D3354", modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "bogster-yellow", modifiers = ["underlined"] }
"markup.link.text" = "bogster-red"
"markup.quote" = "#ff0000"
"markup.raw.inline" = "#23543F"
"markup.raw.block" = "#23543F"

"ui.background" = { bg = "#ECEFF4", fg = "#393D3F" }
"ui.gutter" = { bg = "#ECEFF4" }
"ui.linenr" = { fg = "#C2C8DF" }
"ui.linenr.selected" = { fg = "#5863F8" }
"ui.popup" = { bg = "#D8DEE9", fg = "#ff0000" }
# see ':' menu
"ui.menu" = { bg = "#D8DEE9", fg = "#393D3F" }
"ui.menu.selected" = { bg = "#bbc2cf", fg = "bogster-yellow", modifiers = [
  "italic",
] }
"ui.help" = { bg = "#D8DEE9", fg = "#000000" }
"ui.cursorline" = { bg = "#d7d8e9" }

"diff.plus" = "#297424"
"diff.delta" = "#0D6B70"
"diff.minus" = "bogster-red"


# e.g. Prompt for menus such as GOTO window and multiple key options

"ui.window" = { bg = "#ff0000", fg = "#ff00ff" }


# effects color of bufferline aswell
"ui.statusline" = { bg = "#D8DEE9", fg = "#393D3F" }
"ui.statusline.inactive" = { bg = "#BEC3CC", modifiers = ["dim"] }


"ui.statusline.normal" = { fg = "#000000", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "#8FBFAB", fg = "#000000", modifiers = [
  "bold",
] }
"ui.statusline.select" = { bg = "#BF8FB8", fg = "#000000", modifiers = [
  "bold",
] }


"ui.virtual.wrap" = { fg = "#393D3F", modifiers = ["dim"] }
"ui.virtual.whitespace" = { fg = "#393D3F", modifiers = ["dim"] }
"ui.virtual.indent-guide" = { fg = "#393D3F", modifiers = ["dim"] }
"ui.virtual.inlay-hint" = { bg = "#DFE5F0", fg = "#393D3F", modifiers = [
  "italic",
  "dim",
] }
"ui.virtual.ruler" = { bg = "#E4E6EB", fg = "#ff0000" }


"ui.text" = { fg = "#000000" }
# e.g. file picker -> focused item
"ui.text.focus" = { bg = "#bbc2cf", modifiers = ["bold"] }
# see: <Space> mode prompt and '[' & ']' prompt
"ui.text.info" = { fg = "#2B4162" }

"ui.selection" = { bg = "#C2CDF2" }

"ui.cursor.match" = { modifiers = ["bold", "reversed"] }


"warning" = { fg = "#F08901", modifiers = ["bold"] }
"error" = { fg = "#DB162F", modifiers = ["bold"] }
"info" = { fg = "#393D3F" }
"hint" = { fg = "bogster-blue", modifiers = ["bold"] }

"diagnostic.warning".underline = { color = "#F08901", style = "curl" }
"diagnostic.error".underline = { color = "#DB162F", style = "curl" }
"diagnostic.info".underline = { color = "#393D3F", style = "curl" }
"diagnostic.hint".underline = { color = "bogster-blue", style = "curl" }

[palette]
bogster-yellow = "#020887"
bogster-blue = "#36b2d4"
bogster-red = "#BA160C"
