# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:grey-x11 bg:blk)[](bg:grey-x11 fg:blk)\
[ ](bg:grey-x11 fg:blk)\
[](bg:grey-x11 fg:blk)[](fg:grey-x11 bg:blk)\     
$username$directory[](fg:dark-blue bold)\
$python\
$lua\
$golang\
$git_branch\
$git_status\
$docker_context\
$container\
$memory_usage\
$sudo
[ 󰇥 \\$](fg:227 bold bg:blk)[](fg:blk)[ ]()\
"""


palette = 'foo'

# Inserts a blank line between shell prompts
add_newline = false

[palettes.foo]
grey-x11 = "#BFBDC1"
dark-blue = "#1446A0"
term-bg = "#252525"
blk = "#021320"
sudo-bg = "#BA160C"

[username]
format = "[ $user ]($style)[ ](fg:blk bg:dark-blue)"
show_always = true
style_root = "bg:blk fg:231"
style_user = "bg:blk fg:15 bold"
disabled = false

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bg:dark-blue fg:15"
disabled = false
truncate_to_repo = false
truncation_length = 4
truncation_symbol = "…/"
read_only = "  "

[directory.substitutions]
"Concurrent Programming - 7400" = "Concurrent Prog."
"Downloads" = " "

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[c]
format = '[\[$symbol($version(-$name) )\]]($style)'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'
show_milliseconds = true

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'
ignore_base = true
#disabled = true

[crystal]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[$symbol($version)]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style)"
symbol = ""
style = "dimmed fg:7"
# always_show_remote = true

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
# style = 'dimmed red'
up_to_date = "✓"

[golang]
format = '\[[$symbol($version)]($style)\]'

[haskell]
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'

[julia]
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '[](bold fg:black)[$symbol](bg:black)[${ram_pct}( \${swap})]($style)[](bold fg:black)'
style = 'fg:red bg:black'
threshold = 70
symbol = '🐏'
disabled = false

[nim]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = "[$symbol]($style)"
style = "bg:grey-x11 fg:blk"
disabled = true
[os.symbols]
Macos = " "

[perl]
format = '\[[$symbol($version)]($style)\]'

[php]
format = '\[[$symbol($version)]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
pyenv_version_name = true
python_binary = "python3"

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[scala]
format = '\[[$symbol($version)]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '[$symbol]($style)'
# format = '[](fg:#F5F0F6)[](fg:#BFBDC1)[$symbol]($style)[](fg:#BFBDC1)[](fg:#F5F0F6)'
symbol = '🧙'
# style = "bg:#BFBDC1"
disabled = false

[swift]
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
